### PR TITLE
Fix handling variadic functions

### LINKED ISSUE #55: Incorrect handling variadic parameters
With deepscan and variadic functions, linter exits with panic:
panic: runtime error: index out of range [1] with length 1

goroutine 340 [running]:
github.com/fe3dback/go-arch-lint/internal/services/checker/deepscan.(*Searcher).applyMethodImplementationsInPackages.func1(0x140000f7b00)
        /Users/ilyahontarau/go/src/github.com/ilya-hontarau/go-arch-lint/internal/services/checker/deepscan/searcher_find_implementations.go:137 +0x41c
github.com/fe3dback/go-arch-lint/internal/services/checker/deepscan.(*Searcher).findFunctionCalls.func1({0x10237eb78?, 0x140000f7b00})
        /Users/ilyahontarau/go/src/github.com/ilya-hontarau/go-arch-lint/internal/services/checker/deepscan/searcher_find_implementations.go:245 +0xec
go/ast.inspector.Visit(0x140006406c0, {0x10237eb78?, 0x140000f7b00?})
        /opt/homebrew/opt/go/libexec/src/go/ast/walk.go:386 +0x38
go/ast.Walk({0x102379718?, 0x140006406c0?}, {0x10237eb78, 0x140000f7b00})

### PR DESCRIPTION
**Pull request by ilya-hontarau**
Closes #55

### CODE REVIEW

File: internal/services/checker/deepscan/searcher_find_implementations.go [hunk 1]
```diff
@@ -131,43 +131,53 @@ func (s *Searcher) applyMethodImplementationsInPackages(method *InjectionMethod,
...
 					callMethod := callExpr.Fun
-					callParam := callExpr.Args[gate.Index]
-
-					paramType := astPackage.TypesInfo.TypeOf(callParam)
-					targetName, targetPos, valid := s.extractTargetFromCallParam(paramType)
-					if !valid {
-						// unknown injection type, possible generics or other not known
-						// go features on current moment
-						// we can extend this function later for new cases
+					if gate.IsVariadic && len(callExpr.Args) <= gate.Index {
```
Comment (fe3dback) [inline internal/services/checker/deepscan/searcher_find_implementations.go:134]: It's worth adding a clarifying commentary on what is being tested here and why

File: internal/services/checker/deepscan/searcher_find_implementations.go [hunk 2]
```diff
@@ -131,43 +131,53 @@ func (s *Searcher) applyMethodImplementationsInPackages(method *InjectionMethod,
...
+					if gate.IsVariadic {
+						maxIdx = len(callExpr.Args) - 1
 					}
 
-					if !targetDefinitions.Place.Valid {
-						// invalid target
-						// possible is some not importable std const like `errors`
-						// or not known ast at this moment
-						continue
+					for idx := gate.Index; idx <= maxIdx; idx++ {
```
Comment (fe3dback) [inline internal/services/checker/deepscan/searcher_find_implementations.go:142]: this `idx` is not used anywhere?

File: internal/services/checker/deepscan/models.go [hunk 3]
```diff
@@ -19,6 +19,7 @@ type (
 		ArgumentDefinition Source           // where method param type defined (func (a,b,c _int_))
 		Interface          Interface        // used interface for injection
 		Implementations    []Implementation // all code links to this param
+		IsVariadic         bool             // function param is variadic
```
Comment (fe3dback) [inline internal/services/checker/deepscan/models.go:22]: It would be great to add an example in the comments, like:
```
IsVariadic bool // function param is variadic (func (a bool, nums ...int))
```

**Review by fe3dback — CHANGES_REQUESTED** [review]
Hi, thanks for your contribution, the code looks good, but there are a couple of nuances that should be corrected

File: internal/services/checker/deepscan/searcher_find_implementations.go (hunk 2 above)
Comment (ilya-hontarau) [reply internal/services/checker/deepscan/searcher_find_implementations.go:142]: Oh, thank you, it should be used instead of a `gate.Index.`
Also, do we actually have a test coverage for this part? Maybe it's worth adding it there.

**Review by fe3dback — APPROVED** [review]

**Comment by fe3dback** [comment]
thx, merged in v1.11.3
